#!/usr/bin/env bash
# Same as task 0 but sweet and short
echo -e "sed -iE 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default\
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default\n
pgrep nginx -o > /run/nginx.pid\nnginx -s reload\necho''> /run/nginx.pid" | bash